# Generated by Django 3.0.6 on 2020-05-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertextinput',
            name='text',
            field=models.TextField(),
        ),
    ]
